when@dev:
    web_profiler:
        toolbar: true

    framework:
        profiler:
            collect_serializer_data: true
        http_client:
            default_options:
                extra:
                    trace_id: false

when@test:
    framework:
        profiler:
            collect: false
            collect_serializer_data: true
