<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHHZNMmm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHHZNMmm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHHZNMmm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHHZNMmm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHHZNMmm\App_KernelDevDebugContainer([
    'container.build_hash' => 'HHZNMmm',
    'container.build_id' => '5a150402',
    'container.build_time' => 1774465078,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHHZNMmm');
