<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFmClwpe\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFmClwpe/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFmClwpe.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFmClwpe\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFmClwpe\App_KernelDevDebugContainer([
    'container.build_hash' => 'FmClwpe',
    'container.build_id' => 'b42edead',
    'container.build_time' => 1774272494,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFmClwpe');
